enum Objectif {
    SOURIS, PAPILLON, KINDER, ORANGE, SQUELETTE, POMME, LAPIN, FLATCRAFT, MANETTE, DRAGON, PIZZA, SWITCH, TRESOR, SCARABEE, ABEILLE, ECUREUIL, GRENOUILLE, PORCINET, CHAT, CD, GUITARE, LUTIN, CLOWN, SOLEIL
}
