enum Objectif {
    SOURIS, PAPILLON, KINDER, GNOME, SQUELETTE, POMME, LAPIN, FLATCRAFT, CHANDELIER, FANTOME, PIZZA, TELESCOPE, TRESOR, SCARABEE, ABEILLE, ECUREUIL, GRENOUILLE, PHARAON, CHAT, CD, GUITARE, LUTIN, CLOWN, SOLEIL
}
